#!/usr/bin/env bash
# configures a new Ubuntu machine

# Update package list and install Nginx
apt-get -y update
apt-get -y install nginx

# Add a custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="add_header X-Served-By $HOST_NAME;"
if ! grep -q "X-Served-By" /etc/nginx/sites-available/default; then
    sed -i "server { a $HEADER" /etc/nginx/sites-available/default
fi

# Create a basic index.html page
echo "Hello World!" > /var/www/html/index.html

# Add a redirection to another page
if ! grep -q "redirect_me" /etc/nginx/sites-available/default; then
    sed -i "/server {/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n    }" /etc/nginx/sites-available/default
fi

# Add a custom 404 error page
if ! grep -q "error_page 404" /etc/nginx/sites-available/default; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sed -i "/server {/a \    error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
fi

# Check Nginx configuration for validity
nginx -t
if [ $? -eq 0 ]; then
    # Restart Nginx to apply the changes
    systemctl restart nginx
else
    echo "Nginx configuration is invalid."
fi

# Ensure Nginx is enabled to start on boot
systemctl enable nginx

