#!/usr/bin/env bash
# Script that doubles the number of webservers and adds new configs

# Install nginx (requires root privileges)
sudo apt-get update
sudo apt-get -y install nginx

# Add custom HTTP response header to nginx config
string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf

# Restart nginx service (requires root privileges)
sudo service nginx restart

